### ISSUE TITLE
doesn't decode &Amp; - purposeful?

### ISSUE THREAD

**Issue by sbauch** [threedaymonk/htmlentities#25]
I'm scraping so I can't really control the HTML entity itself. I don't know whether `&Amp;` is a valid html entity (as opposed to `&amp;`), tbh I don't really care, I just need to decode it to &.

The regex to match an entity is case insensitive, but the map (even the expanded flavor) doesn't include the capitalized version. I figure this may have done on purpose to match html specs.

I'm happy to submit a PR to handle this if anyone is interested, but short of that I'm curious what the advised path is. 

My first thought (as seen in other issues) would be to define a custom mapping that includes this value. Being wary of what other entities might be out there that are mis-capitalized, another thought is to downcase the match before checking the map.

**Comment by threedaymonk** [comment]
Unfortunately, there's not a simple solution to this, because the case of entity names matters: `&Uuml;` (Ü) is different from `&uuml;` (ü).

I don't know that there is a good solution. Writing something that falls back to a case-insensitive match when the case-sensitive match fails would be possible, but I doubt it has enough general utility to be worthwhile: this is the first time I've seen this problem. Some kind of custom mapping is probably the way to go, but whilst I've played around with some thoughts in that direction, the API doesn't facilitate that at present.

In your situation, I think I might tack on an extra post-processing step that catches and fixes any errant `&Amp;` along with anything else you come across.
