### ISSUE TITLE
Decode of TM symbol inconsistent between entity name and code

### ISSUE THREAD

**Issue by rjswenson** [threedaymonk/htmlentities#26]
````ruby

HTMLEntities.new.decode("&#153;")
=> "\u0099"

HTMLEntities.new.decode("&trade;")
=> "™"

````

**Comment by threedaymonk** [comment]
The problem is that HTMLEntities only works with Unicode, and your first example is using a different encoding for the entities: Windows-1252, I think. Unicode doesn't define anything at 0x153, so you get an escape sequence for a nonexistent codepoint.

`TRADE MARK SIGN` ™ is U+2122, which is what you get in the second example.
