### ISSUE TITLE
Improperly decoding apostrophe

### ISSUE THREAD

**Issue by joshminnie** [threedaymonk/htmlentities#33]
When using an apostrophe encoded to `&#39;` from Rails, this is being improperly decoded to an empty string.

To reproduce this problem:
HTMLEntities gem version: 4.3.4
Ruby 2.2.2
Rails 4.2.7

```
$> HTMLEntities.new.decode(HTMLEntities.new.encode("'", :decimal))
 => "'" 
$> HTMLEntities.new.encode("'", :decimal)
 => "&#39;" 
$> ERB::Util.h("'")
 => "&#39;" 
$> ERB::Util.h("'") == HTMLEntities.new.encode("'", :decimal)
 => true 
$> ERB::Util.h("'") === HTMLEntities.new.encode("'", :decimal)
 => true 
$> HTMLEntities.new.decode(ERB::Util.h("'"))
 => "" 
```

I was able to get around this behavior by monkey-patching `prepare`

```diff
class HTMLEntities
  class Decoder
    private

    def prepare(string)
-      string.to_s.encode(Encoding::UTF_8)
+      string.to_s.encode(Encoding::UTF_8).unicode_normalize
    end
  end
end
```

**Comment by threedaymonk** [comment]
The problem seems to be that `ERB::Util.h` returns not a `String`, but an `ActiveSupport::SafeBuffer`, and that the latter does not have behavioural equivalence with `String`.

The simplest fix that requires no monkey-patching is to convert the `SafeBuffer` to a string by calling `to_str` before passing it to `decode`: `to_s` doesn't work because it simply returns another `SafeBuffer`.

I think it's ActiveRecord that's at fault here, by passing off as a string something that isn't, but I'm not totally sure.

**Comment by joshminnie** [comment]
Unfortunately, for me, it still requires the monkey-patch, as it's coming through a third part library, but I will ping the developer of that library with your response. Thank you @threedaymonk!
